import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Bottombar from "@/components/Bottombar";
import LeftSidebar from "@/components/Leftbar";
import Topbar from "@/components/Topbar";
import RightSidebar from "@/components/Rightsidebar";
import { NextAuthProvider } from "@/components/Providers";
import WhatsappLive from "@/components/WhatsappLive";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "HubPost || Nigeria",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthProvider>
        {/* <div className="lg:max-w-[900px] lg:px-16 min-h-screen mx-auto py-8 shadow-xl shadow-green-600 flex flex-col px-8"> */}
        <Topbar/>
        
        <main className="flex flex-row">
          <LeftSidebar/>

          <section className="main-container">
            <div className="w-full max-w-4xl">
              {children} <WhatsappLive/>
            </div>
          </section>

          <RightSidebar/>
        </main>

        <Bottombar/>
        </NextAuthProvider>
      </body>
    </html>
  );
}

// {
//   isEditable && (
//       <div className="flex gap-7 font-bold py-2 px-4 rounded-md bg-gray-800 w-fit">
//           <Link href={`/edit-post/${id}`}>
//           <Image src={files.edit} alt="edit"/>
//           </Link>
//           <DeleteButton/>
//       </div>
//   )
// }